services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=${SERVER_PORT:-:8080}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=todo
      - DB_SSLMODE=disable
      - JWT_SECRET=your-secret-key
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
      - ./.env:/root/.env
      - ./config.yaml:/root/config.yaml

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    build: .
    command: ["./todo-api", "migrate"]
    volumes:
      - ./migrations:/migrations
      - ./.env:/root/.env
      - ./config.yaml:/root/config.yaml
    depends_on:
      - postgres

volumes:
  pgdata: